In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Sleep_data.csv", encoding='cp1252')

In [3]:
df

,Document - ID,consultant,procedure,ASA,date,RSI,HADS,Insom,ESS,NOSE,...,AirwaySize_chin_lift,AirwaySize_jaw_thrust,trapdoor_epiglottis,P,T,L,Tb,E,simplified treatment_plan,treatment_plan_with_stages
0,TEXTBOX_003_DISE,"Consultant 1, Consultant 2",SEDATION NASENDOSCOPY (DISE),NaN,17.01.23,13,NaN,5.0,05-Feb,1,...,3.0,3.0,no,1,0,0,0,0,[Rhinitis Rx][Sleep Position Modifier][Allergy...,1.[continue Rhinitis Rx][Sleep Position Modifi...
1,TEXTBOX_006_DISE,Consultant 1,SEDATION NASENDOSCOPY (DISE 4.5),NaN,11.06.25,5,NaN,1.0,05-Jan,3,...,2.0,3.0,normal,1,0,1,1,0,[Weight Loss][Procut Palatoplasty][Barbed Suture],1.[Weight Loss]\n2.[Procut Palatoplasty (anter...
2,TEXTBOX_007_DISE,Consultant 1,SEDATION NASENDOSCOPY (DISE 4.5),2,11.06.25,6,NaN,12.0,03-Jan,13,...,NaN,NaN,U-shaped,0,0,0,1,0,[Weight Loss][Rhinitis Rx][Myofunct. Therapy][...,1.Augmentin for pus L OMC [? weight loss][Rhin...
3,TEXTBOX_008_DISE,Consultant 1,SEDATION NASENDOSCOPY (DISE),2,06.12.22,NaN,NaN,NaN,3,NaN,...,2.0,3.0,NaN,1,0,0,2,0,[Rhinitis Rx][Sleep Position Modifier][Allergy...,1.[Rhinitis Rx][Sleep Position Modifier][Aller...
4,TEXTBOX_009_DISE,Consultant 1,SEDATION NASENDOSCOPY (DISE 4.5),2,28.05.25,6,NaN,5.0,19-Oct,0,...,2.0,3.0,normal,2,0,0,2,0,[Weight Loss][MAD][Chinstrap][Sleep Position M...,1.[Weight Loss] – reduce work on neck at GYM –...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
234,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [4]:
df.to_csv("Sleep_data_clean1.csv", encoding='utf-8', index=False)

In [5]:
df = pd.read_csv("Sleep_data_clean1.csv")

In [6]:
df

,Document - ID,consultant,procedure,ASA,date,RSI,HADS,Insom,ESS,NOSE,...,AirwaySize_chin_lift,AirwaySize_jaw_thrust,trapdoor_epiglottis,P,T,L,Tb,E,simplified treatment_plan,treatment_plan_with_stages
0,TEXTBOX_003_DISE,"Consultant 1, Consultant 2",SEDATION NASENDOSCOPY (DISE),NaN,17.01.23,13,NaN,5.0,05-Feb,1,...,3.0,3.0,no,1,0,0,0,0,[Rhinitis Rx][Sleep Position Modifier][Allergy...,1.[continue Rhinitis Rx][Sleep Position Modifi...
1,TEXTBOX_006_DISE,Consultant 1,SEDATION NASENDOSCOPY (DISE 4.5),NaN,11.06.25,5,NaN,1.0,05-Jan,3,...,2.0,3.0,normal,1,0,1,1,0,[Weight Loss][Procut Palatoplasty][Barbed Suture],1.[Weight Loss]\n2.[Procut Palatoplasty (anter...
2,TEXTBOX_007_DISE,Consultant 1,SEDATION NASENDOSCOPY (DISE 4.5),2,11.06.25,6,NaN,12.0,03-Jan,13,...,NaN,NaN,U-shaped,0,0,0,1,0,[Weight Loss][Rhinitis Rx][Myofunct. Therapy][...,1.Augmentin for pus L OMC [? weight loss][Rhin...
3,TEXTBOX_008_DISE,Consultant 1,SEDATION NASENDOSCOPY (DISE),2,06.12.22,NaN,NaN,NaN,3,NaN,...,2.0,3.0,NaN,1,0,0,2,0,[Rhinitis Rx][Sleep Position Modifier][Allergy...,1.[Rhinitis Rx][Sleep Position Modifier][Aller...
4,TEXTBOX_009_DISE,Consultant 1,SEDATION NASENDOSCOPY (DISE 4.5),2,28.05.25,6,NaN,5.0,19-Oct,0,...,2.0,3.0,normal,2,0,0,2,0,[Weight Loss][MAD][Chinstrap][Sleep Position M...,1.[Weight Loss] – reduce work on neck at GYM –...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
234,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [7]:
selected_columns = [

    #Core physiological
    'BMI', 'AHI', 'sAHI',
    'mean_o2 [%]', 'O2_sats_below_90 [%]', 'lowest_O2(SS) [%]',
    'apnoea', 'hypopnoea',

    #Airway/breathing
    'RSI', 'NOSE',
    'Snoring_mouth_closed', 'Snoring_chin_lift',
    'AirwaySize_mouth_closed', 'AirwaySize_chin_lift',

    #Anatomy (VERY IMPORTANT for treatment)
    'tonsils', 'uvula', 'rhinitis', 'DNS',
    'velopharyngeal_collapse [%]',
    'oropharyngeal_collapse [%]',
    'base_of_tongue_collapse [%]',

    #Optional
    'collar_size [cm]',
    'STOP_BANG',
    'ESS',
    'snore_time',
    'Flow',
    'dB',

    #DISE scoring (very useful for treatment)
    'P', 'T', 'L', 'Tb', 'E',

    #TARGET
    'treatment_plan_with_stages'
]

In [8]:
df = df[selected_columns]

In [9]:
df

,BMI,AHI,sAHI,mean_o2 [%],O2_sats_below_90 [%],lowest_O2(SS) [%],apnoea,hypopnoea,RSI,NOSE,...,ESS,snore_time,Flow,dB,P,T,L,Tb,E,treatment_plan_with_stages
0,25,25.8,51,91.4,17.5,72,NaN,NaN,13,1,...,05-Feb,39,NaN,NaN,1,0,0,0,0,1.[continue Rhinitis Rx][Sleep Position Modifi...
1,28.6,36,87,95.0,10.0,70,32,4,5,3,...,05-Jan,NaN,NaN,NaN,1,0,1,1,0,1.[Weight Loss]\n2.[Procut Palatoplasty (anter...
2,24,29,29,94.0,2.0,83,24,3,6,13,...,03-Jan,NaN,NaN,NaN,0,0,0,1,0,1.Augmentin for pus L OMC [? weight loss][Rhin...
3,28.5,21.6,40.2,92.8,8.3,78,NaN,NaN,NaN,NaN,...,3,62,NaN,NaN,1,0,0,2,0,1.[Rhinitis Rx][Sleep Position Modifier][Aller...
4,30,24,28,93.0,10.0,81,2,22,6,0,...,19-Oct,NaN,NaN,NaN,2,0,0,2,0,1.[Weight Loss] – reduce work on neck at GYM –...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
234,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [10]:
df.to_csv("ReqData.csv", encoding='utf-8', index=False)

In [11]:
df = df.replace('', pd.NA)
df = df.dropna(how='all').reset_index(drop=True)

In [12]:
missing = df.isnull().sum().sort_values(ascending=False)
print(missing)

Flow                           236
dB                             236
collar_size [cm]               228
apnoea                         176
hypopnoea                      176
snore_time                     151
STOP_BANG                      105
O2_sats_below_90 [%]            89
Snoring_chin_lift               88
DNS                             86
lowest_O2(SS) [%]               86
NOSE                            85
base_of_tongue_collapse [%]     84
RSI                             83
sAHI                            83
rhinitis                        82
uvula                           82
Snoring_mouth_closed            81
AirwaySize_chin_lift            81
velopharyngeal_collapse [%]     80
mean_o2 [%]                     80
BMI                             79
E                               79
AirwaySize_mouth_closed         79
tonsils                         79
P                               79
oropharyngeal_collapse [%]      79
T                               79
AHI                             78
ESS                             78
L                               78
Tb                              78
treatment_plan_with_stages       1
dtype: int64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236 entries, 0 to 235
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   BMI                          157 non-null    object
 1   AHI                          158 non-null    object
 2   sAHI                         153 non-null    object
 3   mean_o2 [%]                  156 non-null    float64
 4   O2_sats_below_90 [%]         147 non-null    float64
 5   lowest_O2(SS) [%]            150 non-null    object
 6   apnoea                       60 non-null     object
 7   hypopnoea                    60 non-null     object
 8   RSI                          153 non-null    object
 9   NOSE                         151 non-null    object
 10  Snoring_mouth_closed         155 non-null    float64
 11  Snoring_chin_lift            148 non-null    float64
 12  AirwaySize_mouth_closed      157 non-null    float64
 13  AirwaySize_chin_lift         155 non-null    float64
 14  tonsils                      157 non-null    object
 15  uvula                        154 non-null    object
 16  rhinitis                     154 non-null    object
 17  DNS                          150 non-null    object
 18  velopharyngeal_collapse [%]  156 non-null    object
 19  oropharyngeal_collapse [%]   157 non-null    object
 20  base_of_tongue_collapse [%]  152 non-null    object
 21  collar_size [cm]             8 non-null      object
 22  STOP_BANG                    131 non-null    object
 23  ESS                          158 non-null    object
 24  snore_time                   85 non-null     object
 25  Flow                         0 non-null      float64
 26  dB                           0 non-null      float64
 27  P                            157 non-null    object
 28  T                            157 non-null    object
 29  L                            158 non-null    object
 30  Tb                           158 non-null    object
 31  E                            157 non-null    object
 32  treatment_plan_with_stages   235 non-null    object
dtypes: float64(8), object(25)
memory usage: 61.0+ KB

In [14]:
df.tail(10)

,BMI,AHI,sAHI,mean_o2 [%],O2_sats_below_90 [%],lowest_O2(SS) [%],apnoea,hypopnoea,RSI,NOSE,...,ESS,snore_time,Flow,dB,P,T,L,Tb,E,treatment_plan_with_stages
226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
227,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
234,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [15]:
df = df.head(159)

In [16]:
df

,BMI,AHI,sAHI,mean_o2 [%],O2_sats_below_90 [%],lowest_O2(SS) [%],apnoea,hypopnoea,RSI,NOSE,...,ESS,snore_time,Flow,dB,P,T,L,Tb,E,treatment_plan_with_stages
0,25,25.8,51,91.4,17.5,72,NaN,NaN,13,1,...,05-Feb,39,NaN,NaN,1,0,0,0,0,1.[continue Rhinitis Rx][Sleep Position Modifi...
1,28.6,36,87,95.0,10.0,70,32,4,5,3,...,05-Jan,NaN,NaN,NaN,1,0,1,1,0,1.[Weight Loss]\n2.[Procut Palatoplasty (anter...
2,24,29,29,94.0,2.0,83,24,3,6,13,...,03-Jan,NaN,NaN,NaN,0,0,0,1,0,1.Augmentin for pus L OMC [? weight loss][Rhin...
3,28.5,21.6,40.2,92.8,8.3,78,NaN,NaN,NaN,NaN,...,3,62,NaN,NaN,1,0,0,2,0,1.[Rhinitis Rx][Sleep Position Modifier][Aller...
4,30,24,28,93.0,10.0,81,2,22,6,0,...,19-Oct,NaN,NaN,NaN,2,0,0,2,0,1.[Weight Loss] – reduce work on neck at GYM –...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,26,24,24,97.0,9.0,82,5,19,7,17,...,5,NaN,NaN,NaN,1,0,2,2,0,1.[Chinstrap] +/- [Mandibular Advancement Devi...
155,35,31,31 (99),95.0,7.0,80,4,27,3,0,...,2,NaN,NaN,NaN,2,0,2,1,0,1.[Weight Loss] [Myofunct. Therapy] continue C...
156,30.4,21,NaN,94.0,2.4,84,11,10,3,15,...,12-Jul,NaN,NaN,NaN,2,2,0,0,0,1.[Weight Loss][Rhinitis Rx – Pirinase OTC][Sl...
157,30,18,25,95.0,3.0,78,NaN,NaN,0,7,...,16,25,NaN,NaN,2,1,1,0,0,1.[Rhinitis Rx] [Chinstrap] [MAD] [Weight loss...
158,27.3,48,54,90.0,25.0,57,NaN,NaN,3,4,...,10-Oct,69,NaN,NaN,1,0,0,2,0,1.[Rhinitis Rx] [VitD] [Chinstrap] [NIPF] [con...

In [17]:
missing = df.isnull().sum().sort_values(ascending=False)
print(missing)

Flow                           159
dB                             159
collar_size [cm]               151
apnoea                          99
hypopnoea                       99
snore_time                      74
STOP_BANG                       28
O2_sats_below_90 [%]            12
Snoring_chin_lift               11
DNS                              9
lowest_O2(SS) [%]                9
NOSE                             8
base_of_tongue_collapse [%]      7
RSI                              6
sAHI                             6
rhinitis                         5
uvula                            5
Snoring_mouth_closed             4
AirwaySize_chin_lift             4
velopharyngeal_collapse [%]      3
mean_o2 [%]                      3
BMI                              2
E                                2
AirwaySize_mouth_closed          2
tonsils                          2
P                                2
oropharyngeal_collapse [%]       2
T                                2
AHI                              1
ESS                              1
L                                1
Tb                               1
treatment_plan_with_stages       1
dtype: int64

In [18]:
df = df[df['treatment_plan_with_stages'].notna()]

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 0 to 158
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   BMI                          156 non-null    object
 1   AHI                          157 non-null    object
 2   sAHI                         152 non-null    object
 3   mean_o2 [%]                  155 non-null    float64
 4   O2_sats_below_90 [%]         146 non-null    float64
 5   lowest_O2(SS) [%]            149 non-null    object
 6   apnoea                       59 non-null     object
 7   hypopnoea                    59 non-null     object
 8   RSI                          152 non-null    object
 9   NOSE                         150 non-null    object
 10  Snoring_mouth_closed         154 non-null    float64
 11  Snoring_chin_lift            147 non-null    float64
 12  AirwaySize_mouth_closed      156 non-null    float64
 13  AirwaySize_chin_lift         154 non-null    float64
 14  tonsils                      156 non-null    object
 15  uvula                        153 non-null    object
 16  rhinitis                     153 non-null    object
 17  DNS                          149 non-null    object
 18  velopharyngeal_collapse [%]  156 non-null    object
 19  oropharyngeal_collapse [%]   157 non-null    object
 20  base_of_tongue_collapse [%]  152 non-null    object
 21  collar_size [cm]             8 non-null      object
 22  STOP_BANG                    130 non-null    object
 23  ESS                          157 non-null    object
 24  snore_time                   85 non-null     object
 25  Flow                         0 non-null      float64
 26  dB                           0 non-null      float64
 27  P                            156 non-null    object
 28  T                            156 non-null    object
 29  L                            157 non-null    object
 30  Tb                           157 non-null    object
 31  E                            156 non-null    object
 32  treatment_plan_with_stages   158 non-null    object
dtypes: float64(8), object(25)
memory usage: 42.0+ KB

In [20]:
df

,BMI,AHI,sAHI,mean_o2 [%],O2_sats_below_90 [%],lowest_O2(SS) [%],apnoea,hypopnoea,RSI,NOSE,...,ESS,snore_time,Flow,dB,P,T,L,Tb,E,treatment_plan_with_stages
0,25,25.8,51,91.4,17.5,72,NaN,NaN,13,1,...,05-Feb,39,NaN,NaN,1,0,0,0,0,1.[continue Rhinitis Rx][Sleep Position Modifi...
1,28.6,36,87,95.0,10.0,70,32,4,5,3,...,05-Jan,NaN,NaN,NaN,1,0,1,1,0,1.[Weight Loss]\n2.[Procut Palatoplasty (anter...
2,24,29,29,94.0,2.0,83,24,3,6,13,...,03-Jan,NaN,NaN,NaN,0,0,0,1,0,1.Augmentin for pus L OMC [? weight loss][Rhin...
3,28.5,21.6,40.2,92.8,8.3,78,NaN,NaN,NaN,NaN,...,3,62,NaN,NaN,1,0,0,2,0,1.[Rhinitis Rx][Sleep Position Modifier][Aller...
4,30,24,28,93.0,10.0,81,2,22,6,0,...,19-Oct,NaN,NaN,NaN,2,0,0,2,0,1.[Weight Loss] – reduce work on neck at GYM –...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,26,24,24,97.0,9.0,82,5,19,7,17,...,5,NaN,NaN,NaN,1,0,2,2,0,1.[Chinstrap] +/- [Mandibular Advancement Devi...
155,35,31,31 (99),95.0,7.0,80,4,27,3,0,...,2,NaN,NaN,NaN,2,0,2,1,0,1.[Weight Loss] [Myofunct. Therapy] continue C...
156,30.4,21,NaN,94.0,2.4,84,11,10,3,15,...,12-Jul,NaN,NaN,NaN,2,2,0,0,0,1.[Weight Loss][Rhinitis Rx – Pirinase OTC][Sl...
157,30,18,25,95.0,3.0,78,NaN,NaN,0,7,...,16,25,NaN,NaN,2,1,1,0,0,1.[Rhinitis Rx] [Chinstrap] [MAD] [Weight loss...
158,27.3,48,54,90.0,25.0,57,NaN,NaN,3,4,...,10-Oct,69,NaN,NaN,1,0,0,2,0,1.[Rhinitis Rx] [VitD] [Chinstrap] [NIPF] [con...

In [21]:
missing = df.isnull().sum().sort_values(ascending=False)
print(missing)

Flow                           158
dB                             158
collar_size [cm]               150
apnoea                          99
hypopnoea                       99
snore_time                      73
STOP_BANG                       28
O2_sats_below_90 [%]            12
Snoring_chin_lift               11
DNS                              9
lowest_O2(SS) [%]                9
NOSE                             8
sAHI                             6
RSI                              6
base_of_tongue_collapse [%]      6
rhinitis                         5
uvula                            5
Snoring_mouth_closed             4
AirwaySize_chin_lift             4
mean_o2 [%]                      3
BMI                              2
E                                2
tonsils                          2
AirwaySize_mouth_closed          2
velopharyngeal_collapse [%]      2
P                                2
T                                2
AHI                              1
oropharyngeal_collapse [%]       1
ESS                              1
L                                1
Tb                               1
treatment_plan_with_stages       0
dtype: int64

In [25]:
categorical_cols = ['tonsils', 'uvula', 'rhinitis', 'DNS', 
                    'Snoring_mouth_closed', 'Snoring_chin_lift']

for col in categorical_cols:
    if col in df.columns:
        # Convert NaN and floats to proper string representation first
        df[col] = df[col].replace([np.nan, None], pd.NA)
        df[col] = df[col].astype(str).str.strip().replace('nan', pd.NA)
        
        # Now safely convert to category
        df[col] = df[col].astype('category')

C:\Users\Askam Datha Prasad\AppData\Local\Temp\ipykernel_29744\121491579.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].replace([np.nan, None], pd.NA)
C:\Users\Askam Datha Prasad\AppData\Local\Temp\ipykernel_29744\121491579.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().replace('nan', pd.NA)
C:\Users\Askam Datha Prasad\AppData\Local\Temp\ipykernel_29744\121491579.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype('category')
C:\Users\Askam Datha Prasad\AppData\Local\Temp\ipykernel_29744\121491579.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].replace([np.nan, None], pd.NA)
C:\Users\Askam Datha Prasad\AppData\Local\Temp\ipykernel_29744\121491579.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().replace('nan', pd.NA)
C:\Users\Askam Datha Prasad\AppData\Local\Temp\ipykernel_29744\121491579.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype('category')
C:\Users\Askam Datha Prasad\AppData\Local\Temp\ipykernel_29744\121491579.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].replace([np.nan, None], pd.NA)
C:\Users\Askam Datha Prasad\AppData\Local\Temp\ipykernel_29744\121491579.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().replace('nan', pd.NA)
C:\Users\Askam Datha Prasad\AppData\Local\Temp\ipykernel_29744\121491579.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype('category')
C:\Users\Askam Datha Prasad\AppData\Local\Temp\ipykernel_29744\121491579.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].replace([np.nan, None], pd.NA)
C:\Users\Askam Datha Prasad\AppData\Local\Temp\ipykernel_29744\121491579.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().replace('nan', pd.NA)
C:\Users\Askam Datha Prasad\AppData\Local\Temp\ipykernel_29744\121491579.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype('category')
C:\Users\Askam Datha Prasad\AppData\Local\Temp\ipykernel_29744\121491579.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].replace([np.nan, None], pd.NA)
C:\Users\Askam Datha Prasad\AppData\Local\Temp\ipykernel_29744\121491579.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().replace('nan', pd.NA)
C:\Users\Askam Datha Prasad\AppData\Local\Temp\ipykernel_29744\121491579.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype('category')
C:\Users\Askam Datha Prasad\AppData\Local\Temp\ipykernel_29744\121491579.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].replace([np.nan, None], pd.NA)
C:\Users\Askam Datha Prasad\AppData\Local\Temp\ipykernel_29744\121491579.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().replace('nan', pd.NA)
C:\Users\Askam Datha Prasad\AppData\Local\Temp\ipykernel_29744\121491579.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype('category')

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 158 entries, 0 to 158
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   BMI                          156 non-null    object
 1   AHI                          157 non-null    object
 2   sAHI                         152 non-null    object
 3   mean_o2 [%]                  155 non-null    float64
 4   O2_sats_below_90 [%]         146 non-null    float64
 5   lowest_O2(SS) [%]            149 non-null    object
 6   apnoea                       59 non-null     object
 7   hypopnoea                    59 non-null     object
 8   RSI                          152 non-null    object
 9   NOSE                         150 non-null    object
 10  Snoring_mouth_closed         154 non-null    category
 11  Snoring_chin_lift            147 non-null    category
 12  AirwaySize_mouth_closed      156 non-null    float64
 13  AirwaySize_chin_lift         154 non-null    float64
 14  tonsils                      158 non-null    category
 15  uvula                        158 non-null    category
 16  rhinitis                     158 non-null    category
 17  DNS                          158 non-null    category
 18  velopharyngeal_collapse [%]  156 non-null    object
 19  oropharyngeal_collapse [%]   157 non-null    object
 20  base_of_tongue_collapse [%]  152 non-null    object
 21  collar_size [cm]             8 non-null      object
 22  STOP_BANG                    130 non-null    object
 23  ESS                          157 non-null    object
 24  snore_time                   85 non-null     object
 25  Flow                         0 non-null      float64
 26  dB                           0 non-null      float64
 27  P                            156 non-null    object
 28  T                            156 non-null    object
 29  L                            157 non-null    object
 30  Tb                           157 non-null    object
 31  E                            156 non-null    object
 32  treatment_plan_with_stages   158 non-null    object
dtypes: category(6), float64(6), object(21)
memory usage: 45.4+ KB

In [27]:
df.head()

,BMI,AHI,sAHI,mean_o2 [%],O2_sats_below_90 [%],lowest_O2(SS) [%],apnoea,hypopnoea,RSI,NOSE,...,ESS,snore_time,Flow,dB,P,T,L,Tb,E,treatment_plan_with_stages
0,25,25.8,51,91.4,17.5,72,NaN,NaN,13,1,...,05-Feb,39,NaN,NaN,1,0,0,0,0,1.[continue Rhinitis Rx][Sleep Position Modifi...
1,28.6,36,87,95.0,10.0,70,32,4,5,3,...,05-Jan,NaN,NaN,NaN,1,0,1,1,0,1.[Weight Loss]\n2.[Procut Palatoplasty (anter...
2,24,29,29,94.0,2.0,83,24,3,6,13,...,03-Jan,NaN,NaN,NaN,0,0,0,1,0,1.Augmentin for pus L OMC [? weight loss][Rhin...
3,28.5,21.6,40.2,92.8,8.3,78,NaN,NaN,NaN,NaN,...,3,62,NaN,NaN,1,0,0,2,0,1.[Rhinitis Rx][Sleep Position Modifier][Aller...
4,30,24,28,93.0,10.0,81,2,22,6,0,...,19-Oct,NaN,NaN,NaN,2,0,0,2,0,1.[Weight Loss] – reduce work on neck at GYM –...

In [28]:
df

,BMI,AHI,sAHI,mean_o2 [%],O2_sats_below_90 [%],lowest_O2(SS) [%],apnoea,hypopnoea,RSI,NOSE,...,ESS,snore_time,Flow,dB,P,T,L,Tb,E,treatment_plan_with_stages
0,25,25.8,51,91.4,17.5,72,NaN,NaN,13,1,...,05-Feb,39,NaN,NaN,1,0,0,0,0,1.[continue Rhinitis Rx][Sleep Position Modifi...
1,28.6,36,87,95.0,10.0,70,32,4,5,3,...,05-Jan,NaN,NaN,NaN,1,0,1,1,0,1.[Weight Loss]\n2.[Procut Palatoplasty (anter...
2,24,29,29,94.0,2.0,83,24,3,6,13,...,03-Jan,NaN,NaN,NaN,0,0,0,1,0,1.Augmentin for pus L OMC [? weight loss][Rhin...
3,28.5,21.6,40.2,92.8,8.3,78,NaN,NaN,NaN,NaN,...,3,62,NaN,NaN,1,0,0,2,0,1.[Rhinitis Rx][Sleep Position Modifier][Aller...
4,30,24,28,93.0,10.0,81,2,22,6,0,...,19-Oct,NaN,NaN,NaN,2,0,0,2,0,1.[Weight Loss] – reduce work on neck at GYM –...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,26,24,24,97.0,9.0,82,5,19,7,17,...,5,NaN,NaN,NaN,1,0,2,2,0,1.[Chinstrap] +/- [Mandibular Advancement Devi...
155,35,31,31 (99),95.0,7.0,80,4,27,3,0,...,2,NaN,NaN,NaN,2,0,2,1,0,1.[Weight Loss] [Myofunct. Therapy] continue C...
156,30.4,21,NaN,94.0,2.4,84,11,10,3,15,...,12-Jul,NaN,NaN,NaN,2,2,0,0,0,1.[Weight Loss][Rhinitis Rx – Pirinase OTC][Sl...
157,30,18,25,95.0,3.0,78,NaN,NaN,0,7,...,16,25,NaN,NaN,2,1,1,0,0,1.[Rhinitis Rx] [Chinstrap] [MAD] [Weight loss...
158,27.3,48,54,90.0,25.0,57,NaN,NaN,3,4,...,10-Oct,69,NaN,NaN,1,0,0,2,0,1.[Rhinitis Rx] [VitD] [Chinstrap] [NIPF] [con...

In [29]:
# Save as a new clean CSV file (Recommended)
df.to_csv("DataFinal.csv", index=False, encoding='utf-8')

print("✅ Dataset saved successfully as 'Sleep_data_clean.csv'")

✅ Dataset saved successfully as 'Sleep_data_clean.csv'