In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("DataFinal.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   BMI                          156 non-null    object
 1   AHI                          157 non-null    object
 2   sAHI                         152 non-null    object
 3   mean_o2 [%]                  155 non-null    float64
 4   O2_sats_below_90 [%]         146 non-null    float64
 5   lowest_O2(SS) [%]            149 non-null    object
 6   apnoea                       59 non-null     object
 7   hypopnoea                    59 non-null     object
 8   RSI                          152 non-null    object
 9   NOSE                         150 non-null    object
 10  Snoring_mouth_closed         154 non-null    float64
 11  Snoring_chin_lift            147 non-null    float64
 12  AirwaySize_mouth_closed      156 non-null    float64
 13  AirwaySize_chin_lift         154 non-null    float64
 14  tonsils                      156 non-null    object
 15  uvula                        153 non-null    object
 16  rhinitis                     153 non-null    object
 17  DNS                          149 non-null    object
 18  velopharyngeal_collapse [%]  156 non-null    object
 19  oropharyngeal_collapse [%]   157 non-null    object
 20  base_of_tongue_collapse [%]  152 non-null    object
 21  collar_size [cm]             8 non-null      object
 22  STOP_BANG                    130 non-null    object
 23  ESS                          157 non-null    object
 24  snore_time                   85 non-null     object
 25  Flow                         0 non-null      float64
 26  dB                           0 non-null      float64
 27  P                            156 non-null    object
 28  T                            156 non-null    object
 29  L                            157 non-null    object
 30  Tb                           157 non-null    object
 31  E                            156 non-null    object
 32  treatment_plan_with_stages   158 non-null    object
dtypes: float64(8), object(25)
memory usage: 40.9+ KB

In [4]:
import pandas as pd
import numpy as np

num_cols = [
    'BMI', 'AHI', 'sAHI',
    'mean_o2 [%]', 'O2_sats_below_90 [%]', 'lowest_O2(SS) [%]',
    'RSI', 'NOSE',
    'velopharyngeal_collapse [%]',
    'oropharyngeal_collapse [%]',
    'base_of_tongue_collapse [%]',
    'AirwaySize_mouth_closed', 'AirwaySize_chin_lift'
]

for col in num_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

print(df[num_cols].dtypes)

BMI                            float64
AHI                            float64
sAHI                           float64
mean_o2 [%]                    float64
O2_sats_below_90 [%]           float64
lowest_O2(SS) [%]              float64
RSI                            float64
NOSE                           float64
velopharyngeal_collapse [%]    float64
oropharyngeal_collapse [%]     float64
base_of_tongue_collapse [%]    float64
AirwaySize_mouth_closed        float64
AirwaySize_chin_lift           float64
dtype: object

In [5]:
for col in num_cols:
    if col in df.columns:
        median_value = df[col].median(skipna=True)
        df[col] = df[col].fillna(median_value)

In [6]:
df

,BMI,AHI,sAHI,mean_o2 [%],O2_sats_below_90 [%],lowest_O2(SS) [%],apnoea,hypopnoea,RSI,NOSE,...,ESS,snore_time,Flow,dB,P,T,L,Tb,E,treatment_plan_with_stages
0,25.0,25.8,51.0,91.4,17.5,72.0,NaN,NaN,13.0,1.0,...,05-Feb,39,NaN,NaN,1,0,0,0,0,1.[continue Rhinitis Rx][Sleep Position Modifi...
1,28.6,36.0,87.0,95.0,10.0,70.0,32,4,5.0,3.0,...,05-Jan,NaN,NaN,NaN,1,0,1,1,0,1.[Weight Loss]\n2.[Procut Palatoplasty (anter...
2,24.0,29.0,29.0,94.0,2.0,83.0,24,3,6.0,13.0,...,03-Jan,NaN,NaN,NaN,0,0,0,1,0,1.Augmentin for pus L OMC [? weight loss][Rhin...
3,28.5,21.6,40.2,92.8,8.3,78.0,NaN,NaN,7.0,8.0,...,3,62,NaN,NaN,1,0,0,2,0,1.[Rhinitis Rx][Sleep Position Modifier][Aller...
4,30.0,24.0,28.0,93.0,10.0,81.0,2,22,6.0,0.0,...,19-Oct,NaN,NaN,NaN,2,0,0,2,0,1.[Weight Loss] – reduce work on neck at GYM –...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,26.0,24.0,24.0,97.0,9.0,82.0,5,19,7.0,17.0,...,5,NaN,NaN,NaN,1,0,2,2,0,1.[Chinstrap] +/- [Mandibular Advancement Devi...
154,35.0,31.0,44.0,95.0,7.0,80.0,4,27,3.0,0.0,...,2,NaN,NaN,NaN,2,0,2,1,0,1.[Weight Loss] [Myofunct. Therapy] continue C...
155,30.4,21.0,44.0,94.0,2.4,84.0,11,10,3.0,15.0,...,12-Jul,NaN,NaN,NaN,2,2,0,0,0,1.[Weight Loss][Rhinitis Rx – Pirinase OTC][Sl...
156,30.0,18.0,25.0,95.0,3.0,78.0,NaN,NaN,0.0,7.0,...,16,25,NaN,NaN,2,1,1,0,0,1.[Rhinitis Rx] [Chinstrap] [MAD] [Weight loss...
157,27.3,48.0,54.0,90.0,25.0,57.0,NaN,NaN,3.0,4.0,...,10-Oct,69,NaN,NaN,1,0,0,2,0,1.[Rhinitis Rx] [VitD] [Chinstrap] [NIPF] [con...

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   BMI                          158 non-null    float64
 1   AHI                          158 non-null    float64
 2   sAHI                         158 non-null    float64
 3   mean_o2 [%]                  158 non-null    float64
 4   O2_sats_below_90 [%]         158 non-null    float64
 5   lowest_O2(SS) [%]            158 non-null    float64
 6   apnoea                       59 non-null     object
 7   hypopnoea                    59 non-null     object
 8   RSI                          158 non-null    float64
 9   NOSE                         158 non-null    float64
 10  Snoring_mouth_closed         154 non-null    float64
 11  Snoring_chin_lift            147 non-null    float64
 12  AirwaySize_mouth_closed      158 non-null    float64
 13  AirwaySize_chin_lift         158 non-null    float64
 14  tonsils                      156 non-null    object
 15  uvula                        153 non-null    object
 16  rhinitis                     153 non-null    object
 17  DNS                          149 non-null    object
 18  velopharyngeal_collapse [%]  158 non-null    float64
 19  oropharyngeal_collapse [%]   158 non-null    float64
 20  base_of_tongue_collapse [%]  158 non-null    float64
 21  collar_size [cm]             8 non-null      object
 22  STOP_BANG                    130 non-null    object
 23  ESS                          157 non-null    object
 24  snore_time                   85 non-null     object
 25  Flow                         0 non-null      float64
 26  dB                           0 non-null      float64
 27  P                            156 non-null    object
 28  T                            156 non-null    object
 29  L                            157 non-null    object
 30  Tb                           157 non-null    object
 31  E                            156 non-null    object
 32  treatment_plan_with_stages   158 non-null    object
dtypes: float64(17), object(16)
memory usage: 40.9+ KB

In [8]:
print(df.isna().sum())

BMI                              0
AHI                              0
sAHI                             0
mean_o2 [%]                      0
O2_sats_below_90 [%]             0
lowest_O2(SS) [%]                0
apnoea                          99
hypopnoea                       99
RSI                              0
NOSE                             0
Snoring_mouth_closed             4
Snoring_chin_lift               11
AirwaySize_mouth_closed          0
AirwaySize_chin_lift             0
tonsils                          2
uvula                            5
rhinitis                         5
DNS                              9
velopharyngeal_collapse [%]      0
oropharyngeal_collapse [%]       0
base_of_tongue_collapse [%]      0
collar_size [cm]               150
STOP_BANG                       28
ESS                              1
snore_time                      73
Flow                           158
dB                             158
P                                2
T                                2
L                                1
Tb                               1
E                                2
treatment_plan_with_stages       0
dtype: int64

In [9]:
# Categorical columns (mode)
cat_cols = [
    'tonsils', 'uvula', 'rhinitis', 'DNS',
    'Snoring_mouth_closed', 'Snoring_chin_lift',
    'P', 'T', 'L', 'Tb', 'E'
]

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [10]:
print(df.isna().sum())

BMI                              0
AHI                              0
sAHI                             0
mean_o2 [%]                      0
O2_sats_below_90 [%]             0
lowest_O2(SS) [%]                0
apnoea                          99
hypopnoea                       99
RSI                              0
NOSE                             0
Snoring_mouth_closed             0
Snoring_chin_lift                0
AirwaySize_mouth_closed          0
AirwaySize_chin_lift             0
tonsils                          0
uvula                            0
rhinitis                         0
DNS                              0
velopharyngeal_collapse [%]      0
oropharyngeal_collapse [%]       0
base_of_tongue_collapse [%]      0
collar_size [cm]               150
STOP_BANG                       28
ESS                              1
snore_time                      73
Flow                           158
dB                             158
P                                0
T                                0
L                                0
Tb                               0
E                                0
treatment_plan_with_stages       0
dtype: int64

In [11]:
cols = ['STOP_BANG', 'ESS', 'collar_size [cm]']

for col in cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')
        print(f"✅ {col} converted to numeric. Remaining NaNs: {df[col].isna().sum()}")
    else:
        print(f"Column '{col}' not found in dataframe")

print(df[cols].dtypes)

✅ STOP_BANG converted to numeric. Remaining NaNs: 32
✅ ESS converted to numeric. Remaining NaNs: 97
✅ collar_size [cm] converted to numeric. Remaining NaNs: 151
STOP_BANG           float64
ESS                 float64
collar_size [cm]    float64
dtype: object

In [12]:
for col in cols:
    if col in df.columns:
        # Calculate median (ignoring NaNs)
        median_value = df[col].median()
        
        # Fill NaNs with median
        df[col] = df[col].fillna(median_value)
        
        print(f"✅ {col} → Filled with median = {median_value:.2f} | Remaining NaNs: {df[col].isna().sum()}")

✅ STOP_BANG → Filled with median = 5.00 | Remaining NaNs: 0
✅ ESS → Filled with median = 10.00 | Remaining NaNs: 0
✅ collar_size [cm] → Filled with median = 43.00 | Remaining NaNs: 0

In [13]:
print(df.isna().sum())

BMI                              0
AHI                              0
sAHI                             0
mean_o2 [%]                      0
O2_sats_below_90 [%]             0
lowest_O2(SS) [%]                0
apnoea                          99
hypopnoea                       99
RSI                              0
NOSE                             0
Snoring_mouth_closed             0
Snoring_chin_lift                0
AirwaySize_mouth_closed          0
AirwaySize_chin_lift             0
tonsils                          0
uvula                            0
rhinitis                         0
DNS                              0
velopharyngeal_collapse [%]      0
oropharyngeal_collapse [%]       0
base_of_tongue_collapse [%]      0
collar_size [cm]                 0
STOP_BANG                        0
ESS                              0
snore_time                      73
Flow                           158
dB                             158
P                                0
T                                0
L                                0
Tb                               0
E                                0
treatment_plan_with_stages       0
dtype: int64

In [14]:
df

,BMI,AHI,sAHI,mean_o2 [%],O2_sats_below_90 [%],lowest_O2(SS) [%],apnoea,hypopnoea,RSI,NOSE,...,ESS,snore_time,Flow,dB,P,T,L,Tb,E,treatment_plan_with_stages
0,25.0,25.8,51.0,91.4,17.5,72.0,NaN,NaN,13.0,1.0,...,10.0,39,NaN,NaN,1,0,0,0,0,1.[continue Rhinitis Rx][Sleep Position Modifi...
1,28.6,36.0,87.0,95.0,10.0,70.0,32,4,5.0,3.0,...,10.0,NaN,NaN,NaN,1,0,1,1,0,1.[Weight Loss]\n2.[Procut Palatoplasty (anter...
2,24.0,29.0,29.0,94.0,2.0,83.0,24,3,6.0,13.0,...,10.0,NaN,NaN,NaN,0,0,0,1,0,1.Augmentin for pus L OMC [? weight loss][Rhin...
3,28.5,21.6,40.2,92.8,8.3,78.0,NaN,NaN,7.0,8.0,...,3.0,62,NaN,NaN,1,0,0,2,0,1.[Rhinitis Rx][Sleep Position Modifier][Aller...
4,30.0,24.0,28.0,93.0,10.0,81.0,2,22,6.0,0.0,...,10.0,NaN,NaN,NaN,2,0,0,2,0,1.[Weight Loss] – reduce work on neck at GYM –...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,26.0,24.0,24.0,97.0,9.0,82.0,5,19,7.0,17.0,...,5.0,NaN,NaN,NaN,1,0,2,2,0,1.[Chinstrap] +/- [Mandibular Advancement Devi...
154,35.0,31.0,44.0,95.0,7.0,80.0,4,27,3.0,0.0,...,2.0,NaN,NaN,NaN,2,0,2,1,0,1.[Weight Loss] [Myofunct. Therapy] continue C...
155,30.4,21.0,44.0,94.0,2.4,84.0,11,10,3.0,15.0,...,10.0,NaN,NaN,NaN,2,2,0,0,0,1.[Weight Loss][Rhinitis Rx – Pirinase OTC][Sl...
156,30.0,18.0,25.0,95.0,3.0,78.0,NaN,NaN,0.0,7.0,...,16.0,25,NaN,NaN,2,1,1,0,0,1.[Rhinitis Rx] [Chinstrap] [MAD] [Weight loss...
157,27.3,48.0,54.0,90.0,25.0,57.0,NaN,NaN,3.0,4.0,...,10.0,69,NaN,NaN,1,0,0,2,0,1.[Rhinitis Rx] [VitD] [Chinstrap] [NIPF] [con...

In [15]:
kaggle_dataset = pd.read_csv("ssdb_dataset.csv")

In [16]:
kaggle_dataset

,Patient_ID,Age,Gender,BMI,Snoring,Oxygen_Saturation,AHI,ECG_Heart_Rate,SpO2,Nasal_Airflow,Chest_Movement,Diagnosis_of_SDB,Severity,Treatment_Required,CPAP,Surgery,Physician_Notes,Patient_Symptoms,EEG_Sleep_Stage
0,P1000,56,Female,27.201347,False,96.963387,42.996069,90,96.270135,0.508920,0.117012,Severe,Mild,True,True,False,Patient reports difficulty breathing during sl...,"No issues related to sleep, feels rested.",NREM
1,P1001,69,Male,38.520027,True,89.655429,9.413716,68,90.901309,0.450082,0.799718,NaN,Severe,True,False,False,No significant complaints related to sleep.,Snoring and feeling fatigued after sleep.,REM
2,P1002,46,Female,37.053406,True,91.828302,26.970851,75,95.678616,0.349422,0.123233,Mild,Moderate,True,True,False,Reports waking up multiple times due to breath...,"Patient reports daytime sleepiness, difficulty...",NREM
3,P1003,32,Male,18.994811,False,85.174308,11.752190,78,92.210546,0.220196,0.698531,Mild,NaN,True,True,True,"Family history of sleep apnea, patient reports...","Wakes up frequently at night, choking sensation.",NREM
4,P1004,60,Male,18.580073,True,86.086703,19.610417,71,93.282181,0.450995,0.416145,Moderate,Severe,True,False,False,"Family history of sleep apnea, patient reports...",Frequent waking up due to difficulty breathing.,NREM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,P1495,63,Male,33.230084,False,99.393650,28.285086,74,90.838102,0.388347,0.143395,NaN,Moderate,False,False,True,"Family history of sleep apnea, patient reports...","Patient reports daytime sleepiness, difficulty...",NREM
496,P1496,41,Female,36.682304,False,92.317811,24.369233,71,92.959356,0.462422,0.018386,Moderate,NaN,False,False,False,"Mild snoring observed, no complaints of sleep ...","Snoring and tiredness during the day, family h...",REM
497,P1497,67,Male,23.492696,True,86.646043,19.262596,80,87.770105,0.423832,0.464067,Mild,Mild,False,True,False,Reports excessive tiredness and frequent episo...,"Shortness of breath during sleep, frequent fat...",REM
498,P1498,49,Male,28.767349,True,93.219392,24.556818,66,97.207742,0.474816,0.943062,NaN,Mild,True,False,False,"Choking sensation while sleeping, snoring pres...","Wakes up frequently at night, choking sensation.",REM
499,P1499,64,Male,22.866608,False,91.815660,39.824585,72,85.086868,0.463233,0.323820,Moderate,Moderate,False,False,True,Patient reports frequent snoring and daytime f...,"Shortness of breath during sleep, frequent fat...",NREM

In [17]:
kaggle_dataset.head()

,Patient_ID,Age,Gender,BMI,Snoring,Oxygen_Saturation,AHI,ECG_Heart_Rate,SpO2,Nasal_Airflow,Chest_Movement,Diagnosis_of_SDB,Severity,Treatment_Required,CPAP,Surgery,Physician_Notes,Patient_Symptoms,EEG_Sleep_Stage
0,P1000,56,Female,27.201347,False,96.963387,42.996069,90,96.270135,0.508920,0.117012,Severe,Mild,True,True,False,Patient reports difficulty breathing during sl...,"No issues related to sleep, feels rested.",NREM
1,P1001,69,Male,38.520027,True,89.655429,9.413716,68,90.901309,0.450082,0.799718,NaN,Severe,True,False,False,No significant complaints related to sleep.,Snoring and feeling fatigued after sleep.,REM
2,P1002,46,Female,37.053406,True,91.828302,26.970851,75,95.678616,0.349422,0.123233,Mild,Moderate,True,True,False,Reports waking up multiple times due to breath...,"Patient reports daytime sleepiness, difficulty...",NREM
3,P1003,32,Male,18.994811,False,85.174308,11.752190,78,92.210546,0.220196,0.698531,Mild,NaN,True,True,True,"Family history of sleep apnea, patient reports...","Wakes up frequently at night, choking sensation.",NREM
4,P1004,60,Male,18.580073,True,86.086703,19.610417,71,93.282181,0.450995,0.416145,Moderate,Severe,True,False,False,"Family history of sleep apnea, patient reports...",Frequent waking up due to difficulty breathing.,NREM

In [18]:
kaggle_df = kaggle_dataset

In [19]:
kaggle_df = kaggle_df[[
    'BMI', 'Snoring', 'SpO2',
    'Nasal_Airflow', 'Chest_Movement',
    'AHI'
]]

In [20]:
kaggle_df = kaggle_df.copy()
kaggle_df['Snoring'] = kaggle_df['Snoring'].astype(int)
print(kaggle_df['Snoring'].dtype)

int64

In [21]:
kaggle_df = kaggle_df.dropna()

In [22]:
kaggle_df

           BMI  Snoring       SpO2  Nasal_Airflow  Chest_Movement        AHI
0    27.201347        0  96.270135       0.508920        0.117012  42.996069
1    38.520027        1  90.901309       0.450082        0.799718   9.413716
2    37.053406        1  95.678616       0.349422        0.123233  26.970851
3    18.994811        0  92.210546       0.220196        0.698531  11.752190
4    18.580073        1  93.282181       0.450995        0.416145  19.610417
..         ...      ...        ...            ...             ...        ...
495  33.230084        0  90.838102       0.388347        0.143395  28.285086
496  36.682304        0  92.959356       0.462422        0.018386  24.369233
497  23.492696        1  87.770105       0.423832        0.464067  19.262596
498  28.767349        1  97.207742       0.474816        0.943062  24.556818
499  22.866608        0  85.086868       0.463233        0.323820  39.824585

[500 rows x 6 columns]

In [23]:
from sklearn.ensemble import RandomForestRegressor

X_apnoea = kaggle_df[['BMI', 'Snoring', 'SpO2', 'Nasal_Airflow', 'Chest_Movement']]
y_apnoea = kaggle_df['AHI'] * 0.6

model_apnoea = RandomForestRegressor(n_estimators=100, random_state=42)
model_apnoea.fit(X_apnoea, y_apnoea)

RandomForestRegressor(random_state=42)

In [24]:
X_hypopnoea = X_apnoea
y_hypopnoea = kaggle_df['AHI'] * 0.4

model_hypopnoea = RandomForestRegressor(n_estimators=100, random_state=42)
model_hypopnoea.fit(X_hypopnoea, y_hypopnoea)

RandomForestRegressor(random_state=42)

In [25]:
X_flow = kaggle_df[['BMI', 'Snoring', 'SpO2', 'Chest_Movement']]
y_flow = kaggle_df['Nasal_Airflow']

model_flow = RandomForestRegressor(n_estimators=100, random_state=42)
model_flow.fit(X_flow, y_flow)

RandomForestRegressor(random_state=42)

In [26]:
# Create synthetic snore_time
kaggle_df['snore_time'] = kaggle_df['Snoring'] * (1 - kaggle_df['Nasal_Airflow'])

X_snore = kaggle_df[['BMI', 'Snoring', 'SpO2', 'Nasal_Airflow']]
y_snore = kaggle_df['snore_time']

model_snore = RandomForestRegressor(n_estimators=100, random_state=42)
model_snore.fit(X_snore, y_snore)

RandomForestRegressor(random_state=42)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   BMI                          158 non-null    float64
 1   AHI                          158 non-null    float64
 2   sAHI                         158 non-null    float64
 3   mean_o2 [%]                  158 non-null    float64
 4   O2_sats_below_90 [%]         158 non-null    float64
 5   lowest_O2(SS) [%]            158 non-null    float64
 6   apnoea                       59 non-null     object
 7   hypopnoea                    59 non-null     object
 8   RSI                          158 non-null    float64
 9   NOSE                         158 non-null    float64
 10  Snoring_mouth_closed         158 non-null    float64
 11  Snoring_chin_lift            158 non-null    float64
 12  AirwaySize_mouth_closed      158 non-null    float64
 13  AirwaySize_chin_lift         158 non-null    float64
 14  tonsils                      158 non-null    object
 15  uvula                        158 non-null    object
 16  rhinitis                     158 non-null    object
 17  DNS                          158 non-null    object
 18  velopharyngeal_collapse [%]  158 non-null    float64
 19  oropharyngeal_collapse [%]   158 non-null    float64
 20  base_of_tongue_collapse [%]  158 non-null    float64
 21  collar_size [cm]             158 non-null    float64
 22  STOP_BANG                    158 non-null    float64
 23  ESS                          158 non-null    float64
 24  snore_time                   85 non-null     object
 25  Flow                         0 non-null      float64
 26  dB                           0 non-null      float64
 27  P                            158 non-null    object
 28  T                            158 non-null    object
 29  L                            158 non-null    object
 30  Tb                           158 non-null    object
 31  E                            158 non-null    object
 32  treatment_plan_with_stages   158 non-null    object
dtypes: float64(20), object(13)
memory usage: 40.9+ KB

In [28]:
df['Snoring_mouth_closed'] = df['Snoring_mouth_closed'].astype(int)

In [29]:
mask = df['apnoea'].isna()
df.loc[mask, 'apnoea'] = model_apnoea.predict(
    df.loc[mask, ['BMI', 'Snoring_mouth_closed', 'mean_o2 [%]', 'Flow', 'AirwaySize_mouth_closed']]
)
#Train features are not same as Predict features. So error occurs

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- AirwaySize_mouth_closed
- Flow
- Snoring_mouth_closed
- mean_o2 [%]
Feature names seen at fit time, yet now missing:
- Chest_Movement
- Nasal_Airflow
- Snoring
- SpO2

In [32]:
print(df.isna().sum())

BMI                              0
AHI                              0
sAHI                             0
mean_o2 [%]                      0
O2_sats_below_90 [%]             0
lowest_O2(SS) [%]                0
apnoea                          99
hypopnoea                       99
RSI                              0
NOSE                             0
Snoring_mouth_closed             0
Snoring_chin_lift                0
AirwaySize_mouth_closed          0
AirwaySize_chin_lift             0
tonsils                          0
uvula                            0
rhinitis                         0
DNS                              0
velopharyngeal_collapse [%]      0
oropharyngeal_collapse [%]       0
base_of_tongue_collapse [%]      0
collar_size [cm]                 0
STOP_BANG                        0
ESS                              0
snore_time                      73
Flow                           158
dB                             158
P                                0
T                                0
L                                0
Tb                               0
E                                0
treatment_plan_with_stages       0
dtype: int64

In [49]:
print(model_apnoea.feature_names_in_)

['BMI' 'Snoring' 'SpO2' 'Nasal_Airflow' 'Chest_Movement']

In [30]:
temp_X = pd.DataFrame()
temp_X['BMI'] = df.loc[mask, 'BMI']
temp_X['Snoring'] = df.loc[mask, 'Snoring_mouth_closed'].astype(int)
temp_X['SpO2'] = df.loc[mask, 'mean_o2 [%]']
temp_X['Nasal_Airflow'] = df.loc[mask, 'Flow']
temp_X['Chest_Movement'] = df.loc[mask, 'AirwaySize_mouth_closed']

In [31]:
temp_X.isnull().sum()

BMI                0
Snoring            0
SpO2               0
Nasal_Airflow     99
Chest_Movement     0
dtype: int64

In [33]:
mask = df['Flow'].isna()

temp_X = pd.DataFrame()
temp_X['BMI'] = df.loc[mask, 'BMI']
temp_X['Snoring'] = df.loc[mask, 'Snoring_mouth_closed'].astype(int)
temp_X['SpO2'] = df.loc[mask, 'mean_o2 [%]']
temp_X['Chest_Movement'] = df.loc[mask, 'AirwaySize_mouth_closed']

In [34]:
temp_X.isnull().sum()

BMI               0
Snoring           0
SpO2              0
Chest_Movement    0
dtype: int64

In [35]:
df.loc[mask, 'Flow'] = model_flow.predict(temp_X)

In [36]:
temp_X = pd.DataFrame()
temp_X['BMI'] = df.loc[mask, 'BMI']
temp_X['Snoring'] = df.loc[mask, 'Snoring_mouth_closed'].astype(int)
temp_X['SpO2'] = df.loc[mask, 'mean_o2 [%]']
temp_X['Nasal_Airflow'] = df.loc[mask, 'Flow']
temp_X['Chest_Movement'] = df.loc[mask, 'AirwaySize_mouth_closed']

In [37]:
temp_X.isnull().sum()

BMI               0
Snoring           0
SpO2              0
Nasal_Airflow     0
Chest_Movement    0
dtype: int64

In [38]:
df.loc[mask, 'apnoea'] = model_apnoea.predict(temp_X)

In [39]:
print(df.isna().sum())

BMI                              0
AHI                              0
sAHI                             0
mean_o2 [%]                      0
O2_sats_below_90 [%]             0
lowest_O2(SS) [%]                0
apnoea                           0
hypopnoea                       99
RSI                              0
NOSE                             0
Snoring_mouth_closed             0
Snoring_chin_lift                0
AirwaySize_mouth_closed          0
AirwaySize_chin_lift             0
tonsils                          0
uvula                            0
rhinitis                         0
DNS                              0
velopharyngeal_collapse [%]      0
oropharyngeal_collapse [%]       0
base_of_tongue_collapse [%]      0
collar_size [cm]                 0
STOP_BANG                        0
ESS                              0
snore_time                      73
Flow                             0
dB                             158
P                                0
T                                0
L                                0
Tb                               0
E                                0
treatment_plan_with_stages       0
dtype: int64

In [40]:
mask = df['hypopnoea'].isna()

temp_X = pd.DataFrame()
temp_X['BMI'] = df.loc[mask, 'BMI']
temp_X['Snoring'] = df.loc[mask, 'Snoring_mouth_closed'].astype(int)
temp_X['SpO2'] = df.loc[mask, 'mean_o2 [%]']
temp_X['Nasal_Airflow'] = df.loc[mask, 'Flow']
temp_X['Chest_Movement'] = df.loc[mask, 'AirwaySize_mouth_closed']

In [41]:
temp_X.isnull().sum()

BMI               0
Snoring           0
SpO2              0
Nasal_Airflow     0
Chest_Movement    0
dtype: int64

In [42]:
df.loc[mask, 'hypopnoea'] = model_hypopnoea.predict(temp_X)

In [46]:
mask = df['snore_time'].isna()

temp_X = pd.DataFrame()
temp_X['BMI'] = df.loc[mask, 'BMI']
temp_X['Snoring'] = df.loc[mask, 'Snoring_mouth_closed'].astype(int)
temp_X['SpO2'] = df.loc[mask, 'mean_o2 [%]']
temp_X['Nasal_Airflow'] = df.loc[mask, 'Flow']

In [47]:
temp_X.isnull().sum()

BMI              0
Snoring          0
SpO2             0
Nasal_Airflow    0
dtype: int64

In [48]:
df.loc[mask, 'snore_time'] = model_snore.predict(temp_X)

In [51]:
df = df.drop(columns=['dB'])

In [52]:
df

,BMI,AHI,sAHI,mean_o2 [%],O2_sats_below_90 [%],lowest_O2(SS) [%],apnoea,hypopnoea,RSI,NOSE,...,STOP_BANG,ESS,snore_time,Flow,P,T,L,Tb,E,treatment_plan_with_stages
0,25.0,25.8,51.0,91.4,17.5,72.0,14.448044,9.640803,13.0,1.0,...,4.0,10.0,39,0.380035,1,0,0,0,0,1.[continue Rhinitis Rx][Sleep Position Modifi...
1,28.6,36.0,87.0,95.0,10.0,70.0,18.242617,4,5.0,3.0,...,5.0,10.0,0.687575,0.312668,1,0,1,1,0,1.[Weight Loss]\n2.[Procut Palatoplasty (anter...
2,24.0,29.0,29.0,94.0,2.0,83.0,16.484897,3,6.0,13.0,...,3.0,10.0,0.624197,0.375290,0,0,0,1,0,1.Augmentin for pus L OMC [? weight loss][Rhin...
3,28.5,21.6,40.2,92.8,8.3,78.0,18.328088,12.173105,7.0,8.0,...,2.0,3.0,62,0.301983,1,0,0,2,0,1.[Rhinitis Rx][Sleep Position Modifier][Aller...
4,30.0,24.0,28.0,93.0,10.0,81.0,16.302745,22,6.0,0.0,...,5.0,10.0,0.68501,0.315372,2,0,0,2,0,1.[Weight Loss] – reduce work on neck at GYM –...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,26.0,24.0,24.0,97.0,9.0,82.0,13.414461,19,7.0,17.0,...,5.0,5.0,0.650388,0.349603,1,0,2,2,0,1.[Chinstrap] +/- [Mandibular Advancement Devi...
154,35.0,31.0,44.0,95.0,7.0,80.0,18.317725,27,3.0,0.0,...,5.0,2.0,0.649106,0.351189,2,0,2,1,0,1.[Weight Loss] [Myofunct. Therapy] continue C...
155,30.4,21.0,44.0,94.0,2.4,84.0,17.396078,10,3.0,15.0,...,5.0,10.0,0.687959,0.313742,2,2,0,0,0,1.[Weight Loss][Rhinitis Rx – Pirinase OTC][Sl...
156,30.0,18.0,25.0,95.0,3.0,78.0,16.992484,11.571154,0.0,7.0,...,5.0,16.0,25,0.314225,2,1,1,0,0,1.[Rhinitis Rx] [Chinstrap] [MAD] [Weight loss...
157,27.3,48.0,54.0,90.0,25.0,57.0,13.190995,8.651744,3.0,4.0,...,4.0,10.0,69,0.343978,1,0,0,2,0,1.[Rhinitis Rx] [VitD] [Chinstrap] [NIPF] [con...

In [53]:
df.to_csv("cleaned_sleep_apnea_dataset.csv", index=False)